COMMAND_TYPE = 'KEYBOARD'  # KEYBOARD, RANDOM
FPS = 15

# Environment
SCALE = 1  # must be int
RES_WIDTH = SCALE * 300*2
RES_HEIGHT = SCALE * 400*2
TILE_SIZE = SCALE * 20

# Robot
ROBOT_SIZE = 0.5
ROBOT_START_X = 5
ROBOT_START_Y = 8

# Sensor
SENSOR_LENGTH = TILE_SIZE * 3*300
MEASUREMENT_SIGMA = TILE_SIZE * 3

# Visualization
GENERATE_PLOTS = False

assert RES_HEIGHT % TILE_SIZE == 0 and RES_WIDTH % TILE_SIZE == 0, "Width and height should be a multiple of TILE_SIZE"
