COMMAND_TYPE = 'RANDOM'  # "KEYBOARD"

# Environment
SCALE = 2  # must be int
RES_WIDTH = SCALE * 300
RES_HEIGHT = SCALE * 400
TILE_SIZE = SCALE * 20

# Robot
ROBOT_SIZE = 0.5
ROBOT_START_X = 5
ROBOT_START_Y = 8

# Sensor
SENSOR_LENGTH = TILE_SIZE * 3
MEASUREMENT_SIGMA = TILE_SIZE / 10

assert RES_HEIGHT % TILE_SIZE == 0 and RES_WIDTH % TILE_SIZE == 0, "Width and height should be a multiple of TILE_SIZE"
