COMMAND_TYPE = "KEYBOARD"  # 'RANDOM'

# Environment
RES_WIDTH = 200
RES_HEIGHT = 400
TILE_SIZE = 20

# Robot
ROBOT_SIZE = 0.5
ROBOT_START_X = 2
ROBOT_START_Y = 1
SENSOR_LENGTH = TILE_SIZE * 3


assert RES_HEIGHT % TILE_SIZE == 0 and RES_WIDTH % TILE_SIZE == 0, "Width and height should be a multiple of TILE_SIZE"
